services:
  - type: web
    name: zoobi-chat-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: zoobi-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: zoobi-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: zoobi-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect

databases:
  - name: zoobi-db
    plan: free
    region: oregon
